### ISSUE TITLE
max_step_rate not initialized

### ISSUE THREAD

**Issue by primtal** [gbr1/rp2040-encoder-library#1]
Hi Giovanni,

great code, thanks for sharing!
I think I found a small issue and wanted to share the finding.
In the constructor:

PioEncoder::PioEncoder(uint8_t _pin, PIO _pio, uint _sm, int max_step_rate){
    static uint offset;
    pin=_pin;
    pio = _pio;
    sm = _sm;
}

the max_step_rate does not initialise the class variable. This results in some unpredictable outcome when embedded in larger code. Sometimes it works, sometimes it fails as the variable might have an unpredictable state. Might depend on the compiler, but I found flaky behaviour when using this with the Arduino IDE.

Cheers,
Roland

**Comment by gbr1** [comment]
Yes! you are right, I missed in the constructor

**Comment by gbr1** [comment]
Hi @primtal 
it should be fixed :D

https://github.com/gbr1/rp2040-encoder-library/releases/tag/0.1.2
