### ISSUE TITLE
getCount() only returning 0 & -1

### ISSUE THREAD

**Issue by Jediknite1101** [gbr1/rp2040-encoder-library#2]
When running the examples I don't actually get a count. The only two values that are printed in the serial monitor are 0 and -1

I'm running a Raspberry Pi Pico, with the [earlephilhower](https://github.com/earlephilhower) board profile.

**Comment by gbr1** [comment]
Hi @Jediknite1101, it should work. Are you using a quadrature encoder placed on two successive pins?

**Comment by Jediknite1101** [comment]
yes, I have two incremental encoders. ENC1 pins 2,3 and ENC2 pins 4,5... The example had pins 2+3 initially.. so that's why I started there

**Comment by Jediknite1101** [comment]
I swapped the data out wires and it seems to work now.
