### ISSUE TITLE
Rotary encoder increments by 4

### ISSUE THREAD

**Issue by heliophagus** [gbr1/rp2040-encoder-library#4]
Hi - thanks for the library! I'm using it with Earle Philhower's RP2040 Arduino core, which is great, on an Adafruit Metro RP2040 & a KY-040 rotary encoder. I'm using 10k pullups on A & B. It works really well. 

This is more of a question than an issue, but - I noticed that the code the rotary encoder increments its count by 4 with each detent, rather than 1. The increment is always exactly 4, which makes it unlikely that it's a bounce issue. Maybe this is a side effect of the code apparently targeting the MBED platform - I get this warning: "WARNING: library rp2040-encoder-library claims to run on mbed_rp2040, mbed_nano architecture(s) and may be incompatible with your current board which runs on rp2040 architecture(s)."

Of course this is trivial to code around! But I'm wondering why this happens.

**Comment by gbr1** [comment]
Hi @heliophagus!
The warning is given automatically by the `architecture` tag inside the library.properties file.

About 4x, generally it comes by the way you read the encoder. Is your encoder in quadrature?

**Comment by heliophagus** [comment]
Thanks, @gbr1. My encoder is the plain-vanilla type, with A, B & Common, so yes, it's a quadrature encoder. No big deal to simply shift the reading to effectively divide by 4. Thanks also for the explanation of the warning.

**Comment by gbr1** [comment]
@heliophagus probably I could add some methods or parameters to set by default 4x reading (as is now) and also 1x (shift by 2) and 2x (shift by 1)

**Comment by heliophagus** [comment]
True! And if you want to do that, it would also be handy to be able to reset the encoder position to a given value rather than only zero. However, both of these options, though useful, can be coded around.

**Comment by gbr1** [comment]
@heliophagus everything is added in https://github.com/gbr1/rp2040-encoder-library/releases/tag/0.2.0
